
package com.gestioncomptes.servicessoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueSoapService", targetNamespace = "http://servicessoap.gestioncomptes.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueSoapService {


    /**
     * 
     * @param size
     * @param codeCcodeCompteSourceompte
     * @param page
     * @return
     *     returns com.gestioncomptes.servicessoap.PageOperation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOperation", targetNamespace = "http://servicessoap.gestioncomptes.com/", className = "com.gestioncomptes.servicessoap.GetOperation")
    @ResponseWrapper(localName = "getOperationResponse", targetNamespace = "http://servicessoap.gestioncomptes.com/", className = "com.gestioncomptes.servicessoap.GetOperationResponse")
    @Action(input = "http://servicessoap.gestioncomptes.com/BanqueSoapService/getOperationRequest", output = "http://servicessoap.gestioncomptes.com/BanqueSoapService/getOperationResponse")
    public PageOperation getOperation(
        @WebParam(name = "codeCcodeCompteSourceompte", targetNamespace = "")
        String codeCcodeCompteSourceompte,
        @WebParam(name = "page", targetNamespace = "")
        int page,
        @WebParam(name = "size", targetNamespace = "")
        int size);

    /**
     * 
     * @param montant
     * @param codeCompte
     * @param codeEmploye
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verser", targetNamespace = "http://servicessoap.gestioncomptes.com/", className = "com.gestioncomptes.servicessoap.Verser")
    @ResponseWrapper(localName = "verserResponse", targetNamespace = "http://servicessoap.gestioncomptes.com/", className = "com.gestioncomptes.servicessoap.VerserResponse")
    @Action(input = "http://servicessoap.gestioncomptes.com/BanqueSoapService/verserRequest", output = "http://servicessoap.gestioncomptes.com/BanqueSoapService/verserResponse")
    public boolean verser(
        @WebParam(name = "codeCompte", targetNamespace = "")
        String codeCompte,
        @WebParam(name = "montant", targetNamespace = "")
        double montant,
        @WebParam(name = "codeEmploye", targetNamespace = "")
        Long codeEmploye);

    /**
     * 
     * @param codeCompte
     * @return
     *     returns com.gestioncomptes.servicessoap.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://servicessoap.gestioncomptes.com/", className = "com.gestioncomptes.servicessoap.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://servicessoap.gestioncomptes.com/", className = "com.gestioncomptes.servicessoap.GetCompteResponse")
    @Action(input = "http://servicessoap.gestioncomptes.com/BanqueSoapService/getCompteRequest", output = "http://servicessoap.gestioncomptes.com/BanqueSoapService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "codeCompte", targetNamespace = "")
        String codeCompte);

    /**
     * 
     * @param montant
     * @param codeCompte
     * @param codeEmploye
     * @return
     *     returns boolean
     * @throws MontantRetraitEleveException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retirer", targetNamespace = "http://servicessoap.gestioncomptes.com/", className = "com.gestioncomptes.servicessoap.Retirer")
    @ResponseWrapper(localName = "retirerResponse", targetNamespace = "http://servicessoap.gestioncomptes.com/", className = "com.gestioncomptes.servicessoap.RetirerResponse")
    @Action(input = "http://servicessoap.gestioncomptes.com/BanqueSoapService/retirerRequest", output = "http://servicessoap.gestioncomptes.com/BanqueSoapService/retirerResponse", fault = {
        @FaultAction(className = MontantRetraitEleveException_Exception.class, value = "http://servicessoap.gestioncomptes.com/BanqueSoapService/retirer/Fault/MontantRetraitEleveException")
    })
    public boolean retirer(
        @WebParam(name = "codeCompte", targetNamespace = "")
        String codeCompte,
        @WebParam(name = "montant", targetNamespace = "")
        double montant,
        @WebParam(name = "codeEmploye", targetNamespace = "")
        Long codeEmploye)
        throws MontantRetraitEleveException_Exception
    ;

    /**
     * 
     * @param codeCcodeCompteSourceompte
     * @param montant
     * @param codeCompteDestination
     * @param codeEmploye
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "virement", targetNamespace = "http://servicessoap.gestioncomptes.com/", className = "com.gestioncomptes.servicessoap.Virement")
    @ResponseWrapper(localName = "virementResponse", targetNamespace = "http://servicessoap.gestioncomptes.com/", className = "com.gestioncomptes.servicessoap.VirementResponse")
    @Action(input = "http://servicessoap.gestioncomptes.com/BanqueSoapService/virementRequest", output = "http://servicessoap.gestioncomptes.com/BanqueSoapService/virementResponse")
    public boolean virement(
        @WebParam(name = "codeCcodeCompteSourceompte", targetNamespace = "")
        String codeCcodeCompteSourceompte,
        @WebParam(name = "codeCompteDestination", targetNamespace = "")
        String codeCompteDestination,
        @WebParam(name = "montant", targetNamespace = "")
        double montant,
        @WebParam(name = "codeEmploye", targetNamespace = "")
        Long codeEmploye);

}
