
package com.gestioncomptes.servicessoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BanqueSoapServiceService", targetNamespace = "http://servicessoap.gestioncomptes.com/", wsdlLocation = "file:/C:/Users/youcef/AppData/Local/Temp/tempdir6638650143704274846.tmp/Banque_1.wsdl")
public class BanqueSoapServiceService
    extends Service
{

    private final static URL BANQUESOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BANQUESOAPSERVICESERVICE_EXCEPTION;
    private final static QName BANQUESOAPSERVICESERVICE_QNAME = new QName("http://servicessoap.gestioncomptes.com/", "BanqueSoapServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/youcef/AppData/Local/Temp/tempdir6638650143704274846.tmp/Banque_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANQUESOAPSERVICESERVICE_WSDL_LOCATION = url;
        BANQUESOAPSERVICESERVICE_EXCEPTION = e;
    }

    public BanqueSoapServiceService() {
        super(__getWsdlLocation(), BANQUESOAPSERVICESERVICE_QNAME);
    }

    public BanqueSoapServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANQUESOAPSERVICESERVICE_QNAME, features);
    }

    public BanqueSoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, BANQUESOAPSERVICESERVICE_QNAME);
    }

    public BanqueSoapServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANQUESOAPSERVICESERVICE_QNAME, features);
    }

    public BanqueSoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanqueSoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueSoapService
     */
    @WebEndpoint(name = "BanqueSoapServicePort")
    public BanqueSoapService getBanqueSoapServicePort() {
        return super.getPort(new QName("http://servicessoap.gestioncomptes.com/", "BanqueSoapServicePort"), BanqueSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueSoapService
     */
    @WebEndpoint(name = "BanqueSoapServicePort")
    public BanqueSoapService getBanqueSoapServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicessoap.gestioncomptes.com/", "BanqueSoapServicePort"), BanqueSoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANQUESOAPSERVICESERVICE_EXCEPTION!= null) {
            throw BANQUESOAPSERVICESERVICE_EXCEPTION;
        }
        return BANQUESOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
