
package com.gestioncomptes.servicessoap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MontantRetraitEleveException", targetNamespace = "http://servicessoap.gestioncomptes.com/")
public class MontantRetraitEleveException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MontantRetraitEleveException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MontantRetraitEleveException_Exception(String message, MontantRetraitEleveException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MontantRetraitEleveException_Exception(String message, MontantRetraitEleveException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.gestioncomptes.servicessoap.MontantRetraitEleveException
     */
    public MontantRetraitEleveException getFaultInfo() {
        return faultInfo;
    }

}
